import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { TbBrandThreads } from "react-icons/tb";
import { CgMenuRightAlt } from "react-icons/cg";
import { BiArrowBack } from "react-icons/bi";

import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Button } from "@/components/ui/button";
import { GoHomeFill, GoPerson } from "react-icons/go";
import { IoSearch } from "react-icons/io5";
import { BsPencilSquare } from "react-icons/bs";
import { FiHeart, FiPlus } from "react-icons/fi";
import { RiInstagramLine } from "react-icons/ri";
import { LuPin } from "react-icons/lu";

export const metadata: Metadata = {
  title: "Home . Threads",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`p-4 pb-0 antialiased  items-end justify-between w-full overflow-hidden md:flex `}
      >
        <aside className="hidden md:flex flex-col justify-between h-screen w-fit px-0 pt-6 py-9">
          <Link href="/">
            <div className="w-full flex justify-center  animate rounded-lg">
              <TbBrandThreads color="white" size={34} className="text-center" />
            </div>
          </Link>
          <nav>
            <ul className="flex flex-col gap-4 text-[#6B6B6B] ">
              <li>
                <Link href="/">
                  <div className="hover:bg-[rgba(71,71,71,0.49)] w-full flex justify-center py-2.5 px-4 animate rounded-lg">
                    <GoHomeFill
                      color=""
                      className="text-white text-[25px] cursor-pointer"
                    />
                  </div>
                </Link>
              </li>
              <li>
                <Link href="/search">
                  <div className="hover:bg-[rgba(71,71,71,0.49)] w-full flex justify-center py-2.5 animate rounded-lg">
                    <IoSearch
                      color=""
                      className="text-white text-[25px] cursor-pointer"
                    />
                  </div>
                </Link>
              </li>
              <div className="hover:bg-[rgba(71,71,71,0.49)] w-full flex justify-center py-2.5 animate rounded-lg">
                <FiPlus
                  color=""
                  className="text-white text-[25px] cursor-pointer"
                />
              </div>
              <li>
                <Link href="/activity">
                  <div className="hover:bg-[rgba(71,71,71,0.49)] w-full flex justify-center py-2.5 animate rounded-lg">
                    <FiHeart
                      color=""
                      className="text-white text-[25px] cursor-pointer"
                    />
                  </div>
                </Link>
              </li>
              <li>
                <Link href="/profile">
                  <div className="hover:bg-[rgba(71,71,71,0.49)] w-full flex justify-center py-2.5 animate rounded-lg">
                    <GoPerson
                      color=""
                      className="text-white text-[25px] cursor-pointer"
                    />
                  </div>
                </Link>
              </li>
            </ul>
          </nav>
          <div className="flex flex-col">
            <button>
              {" "}
              <div className="hover:bg-[rgba(71,71,71,0.49)] w-full flex justify-center py-2.5 animate rounded-lg">
                <LuPin
                  color=""
                  className="text-white text-[25px] cursor-pointer"
                />
              </div>
            </button>
            <button>
              {" "}
              <div className="hover:bg-[rgba(71,71,71,0.49)] w-full flex justify-center py-2.5 animate rounded-lg">
                <CgMenuRightAlt
                  color=""
                  className="text-white text-[25px] cursor-pointer rotate-180"
                />
              </div>
            </button>
          </div>
        </aside>

        <header className="h-[65px] w-full fixed top-0 left-0 pt-4 pb-5 px-4 backdrop-blur-[10px]  bg-[rgba(0,0,0,0.69)] md:hidden">
          <div className="flex  items-center justify-between">
            <Link href={"/"}>
              <BiArrowBack
                size={22}
                className="text-[#4d4d4d] cursor-pointer w-[55px] hover:text-white animate movie opacity-0"
              />
            </Link>
            <Link href="/">
              <TbBrandThreads
                color="white"
                size={34}
                className="hover:scale-[1.1] animate"
              />
            </Link>

            <div className="hidden">
              {" "}
              <DropdownMenu>
                <DropdownMenuTrigger>
                  {" "}
                  <CgMenuRightAlt
                    size={22}
                    className="text-[#4d4d4d] cursor-pointer hover:text-white animate movie"
                  />
                </DropdownMenuTrigger>
                <DropdownMenuContent>
                  <DropdownMenuLabel>My Account</DropdownMenuLabel>
                  <DropdownMenuSeparator />
                  <DropdownMenuItem>Profile</DropdownMenuItem>
                  <DropdownMenuItem>Billing</DropdownMenuItem>
                  <DropdownMenuItem>Team</DropdownMenuItem>
                  <DropdownMenuItem>Subscription</DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
            <Button className="animate bg-white text-black text-[12px] cursor-pointer w-[60px] h-[30px] hover:bg-white">
              Войти
            </Button>
          </div>
        </header>

        <div className="flex items-start gap-2 mx-auto">
          <main className="text-white  w-full mx-auto bg-[#101010]  md:h-[90vh] md:w-[550px] rounded-2xl rounded-b-[0px] overflow-y-auto scroll-none">
            {children}
          </main>
          <div className="hidden w-[310px] bg-[#101010] max-h-[100%] rounded-2xl py-7 px-2.5 md:block">
            <h2 className="text-white font-bold text-xl leading-5 text-center">
              Войдите или <br /> зарегистрируйтесь в Threads
            </h2>
            <p className="text-center text-[15px] text-[#777777] mt-3 font-normal">
              Узнавайте, о чем говорят люди, и вступайте в разговоры.
            </p>
            <button className="w-full py-6 px-5 cursor-pointer bg-[#080808] text-start leading-5 gap-2 rounded-2xl flex items-center  text-[white] text-[16px] font-semibold mt-6">
              <RiInstagramLine className="text-[24px]" />
              Продолжить с аккаунтом <br /> Instagram
            </button>
            <p className="text-center text-[#777777] mt-6 font-normal cursor-pointer">
              Войти по имени пользователя
            </p>
          </div>
        </div>

        <button className="hidden text-white">+</button>

        <div className="h-[65px] w-full fixed bottom-0 left-0 pt-4 pb-5 px-1 backdrop-blur-[10px] flex justify-between items-center bg-[rgba(0,0,0,0.69)] md:hidden">
          <div className="hover:bg-[rgba(71,71,71,0.49)] w-full flex justify-center py-5 animate rounded-lg">
            <GoHomeFill
              color=""
              className="text-white text-[22px] cursor-pointer"
            />
          </div>
          <div className="hover:bg-[rgba(71,71,71,0.49)] w-full flex justify-center py-5 animate rounded-lg">
            <IoSearch
              color=""
              className="text-white text-[22px] cursor-pointer"
            />
          </div>
          <div className="hover:bg-[rgba(71,71,71,0.49)] w-full flex justify-center py-5 animate rounded-lg">
            <BsPencilSquare
              color=""
              className="text-white text-[22px] cursor-pointer"
            />
          </div>
          <div className="hover:bg-[rgba(71,71,71,0.49)] w-full flex justify-center py-5 animate rounded-lg">
            <FiHeart
              color=""
              className="text-white text-[22px] cursor-pointer"
            />
          </div>
          <div className="hover:bg-[rgba(71,71,71,0.49)] w-full flex justify-center py-5 animate rounded-lg">
            <GoPerson
              color=""
              className="text-white text-[22px] cursor-pointer"
            />
          </div>
        </div>
      </body>
    </html>
  );
}
